local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Balligusapo Hub", "DarkTheme")

local Tab = Window:NewTab("Page 1")
local Section = Tab:NewSection("Page 1")
Section:NewButton("Bumper Car", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/jkgEhPUk"))()
end)
Section:NewButton("Shotgun", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/pLdGH4h7"))()
end)
Section:NewButton("Naruto", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/NctKdkfz"))()
end)
Section:NewButton("OnePunch Man", "ButtonInfo", function()
loadstring(game:HttpGet("http://pastebin.com/raw/78r3Tt2B"))()
end)

local Tab = Window:NewTab("Page 2")
local Section = Tab:NewSection("Page 2")
Section:NewButton("Drone", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/k5eWfDYa"))()
end)
Section:NewButton("Cops", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/FR9Fzcqw"))()
end)
Section:NewButton("SlenderMan", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/4AjCBJXv"))()
end)
Section:NewButton("Axe", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/TKYSiZqf"))()
end)

local Tab = Window:NewTab("Page 3")
local Section = Tab:NewSection("Page 3")
Section:NewButton("Gas", "ButtonInfo", function()
loadstring(game:HttpGet("https://pastebin.com/raw/HW208cFY"))()
end)

local Tab = Window:NewTab("Read")
local Section = Tab:NewSection("Note: Its My Scripts!")
Section:NewButton("Updates Soon!", "ButtonInfo", function()
end)
local Section = Tab:NewSection("Adding Customize Gui Color")
local Section = Tab:NewSection("Adding More Scripts")
